kind: pipeline
name: default

steps:
  - name: unit-tests
    image: node:lts-slim
    pull: always
    commands:
      - yarn install
      - yarn run typecheck
      - yarn run test
      - yarn run lint
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: synapse
    when:
      status:
        - failure
trigger:
  event:
    - push
    - pull_request
